// <auto-generated />
using CodeFirstCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstCrud.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("CodeFirstCrud.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Collegename")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
